
# Python NumPy Tutorial for Beginners - Note and Summary
- Youtube Link : https://youtu.be/QUT1VHiLmmI?si=DYAc1pVUMoYnWY9d


# -  


# What is Numpy?

- 1D array
- 2D array
- 3D array

# How are Lists different from Numpy?

- Lists : Slow
- Numpy : Fast

# Why is Numpy Fater?
- Faster to read less bytes of memory
- No type checking when iteratin through objects

# How are Lists different from Numpy?
- Lists
  - Insertion, deletion, appending, concatenation, etc.
  - a = [ 1, 2, 5 ]
  - b = [ 1, 2, 3 ]
  - a*b = ERROR

- NumPy
  - Insertion, deletion, appending, concatenation, etc.
  - a = np.array([ 1, 3, 5 ])
  - b = np.array([ 1, 2, 3 ])
  - a*b = np.array([ 1, 6, 15])

#Applications of NumPy?
  - Mathematics (MATLAB Replacement)
  - Plotting (Matplotlib)
  - Backend (Pandas, Connect 4, Digital Photography)
  - Machine Learning
  

### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [19]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [20]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.26603087, 0.83931728],
       [0.20798719, 0.59939032],
       [0.76473849, 0.58099835],
       [0.82269501, 0.46122215]])

In [26]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  5, -2],
       [ 0,  0,  5],
       [-1,  6,  1]])

In [27]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)
print()

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print()

output[1:-1,1:-1] = z
print(output)
print()

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



##### Be careful when copying arrays!!!

In [30]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print()
print(b)

[1 2 3]

[100   2   3]


### Mathematics

In [31]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a + 2

array([3, 4, 5, 6])

In [33]:
a - 2

array([-1,  0,  1,  2])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [39]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [40]:
a = np.ones((2,3))
print(a)
print()

b = np.full((3,2), 2)
print(b)
print()

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]



array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [42]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [43]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats)

1

In [45]:
np.max(stats, axis=1)

array([3, 6])

In [46]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [47]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [50]:


#filedata = np.genfromtxt('data.txt', delimiter=',')
#filedata = filedata.astype('int32')

#2) 구글 드라이브 내 데이터 파일 읽기 위한 설정
from google.colab import drive

# Mount Google Drive
# drive.mount('/content/drive/')

# file_path = '/content/drive/My Drive/Colab Notebooks/freeCodeCamp_org/data_Python_NumPy_Tutorial_for_Beginners.txt'
# filedata = np.genfromtxt(file_path, delimiter=',')

# filedata = filedata.astype('int32')


# print(filedata)



import numpy as np
from google.colab import drive

# Google Drive 마운트
drive.mount('/content/drive/')



Mounted at /content/drive/


In [51]:
file_path = '/content/drive/My Drive/Colab Notebooks/freeCodeCamp_org/data_Python_NumPy_Tutorial_for_Beginners.txt'

# read file
filedata = np.genfromtxt(file_path, delimiter=',')
filedata = filedata.astype('int32')

# data print
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [52]:
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [53]:
# read text file
f = open(file_path, 'r')
lines = f. readlines()
f. close()
for line in lines:
  print (line)

1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5

3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12

1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88



##### Boolean Masking and Advanced Indexing

In [54]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [55]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [56]:
test = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [57]:
test[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [58]:
test[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
test[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [60]:
test[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])